title: ðŸ‘‹ Hi, I'm Abhinav Gupta # The title of the blog
author: Abhinav Gupta # Your name 
email: iitrabhi@gmail.com # your email shown in the footer

url: "https://abhigupta.io" # this is your site's root address.

permalink: /:year/:month/:day/:title:output_ext


description: > # this means to ignore newlines until "show_excerpts:" 
  Researcher. Developer. Creative Coder
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://www.abhigupta.io/assets/images/abhi-3.jpg" # avatar in about page
  about_you: Research scientist, Indian Institute of Technology Roorkee # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: abhiguptaio
    github:  iitrabhi
    scholar: UfWvIkEAAAAJ
    researchgate: Abhinav_Gupta52
    # rss: RSS
    # dribbble: 
    # facebook: 
    # flickr:   
    # instagram: 
    # linkedin: 
    # pinterest: 
    # youtube: channel/UCpj8oznjjLwVe5KHOGNrvnQ
    youtube_channel: UCpj8oznjjLwVe5KHOGNrvnQ
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
# remote_theme: iitrabhi/moving
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag



# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-9W3VPP9B40

# Text under the icons in footer
footer-text:

# JavaScript
# head_scripts:
#   - /assets/js/two.min.js

# https://jekyllrb.com/docs/collections/
collections:
  projects:
    output: true
  newsletters:
    output: true

# Compress CSS files
sass:
    style: compressed

highlighter: rouge
# gist:
#   noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge